from io import BytesIO
from django.http import HttpResponse
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime
import os
from django.conf import settings

def generate_land_report_pdf(land_data, request):
    """Generate PDF report for land analysis"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1*inch, bottomMargin=1*inch)
    
    # Create styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        spaceAfter=30,
        alignment=TA_CENTER,
        textColor=colors.HexColor('#2e7d32')
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        spaceAfter=12,
        textColor=colors.HexColor('#1b5e20')
    )
    
    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=10,
        spaceAfter=6
    )
    
    # Build the story (content)
    story = []
    
    # Title
    story.append(Paragraph("AgriSite - Land Analysis Report", title_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Report metadata
    story.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M')}", normal_style))
    story.append(Paragraph(f"Generated by: {request.user.username}", normal_style))
    story.append(Spacer(1, 0.3*inch))
    
    # Summary Statistics
    story.append(Paragraph("Summary Statistics", heading_style))
    
    summary_data = [
        ['Metric', 'Value'],
        ['Total Land Holders', land_data.get('total_land_holders', 0)],
        ['Total Land Parcels', land_data.get('total_parcels', 0)],
        ['Total Cultivated Area', f"{land_data.get('total_cultivated_area', 0):.2f} hectares"],
        ['Average Productivity Score', f"{land_data.get('avg_productivity', 0):.1f}%"]
    ]
    
    summary_table = Table(summary_data, colWidths=[3*inch, 2*inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2e7d32')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey)
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 0.3*inch))
    
    # Land Holding Analysis
    if 'land_holding_analysis' in land_data:
        story.append(Paragraph("Land Holding Analysis", heading_style))
        
        holding_data = [['Ownership Type', 'Count', 'Total Land (ha)', 'Avg Parcels']]
        for item in land_data['land_holding_analysis']:
            holding_data.append([
                item.get('ownership_type', '').title(),
                item.get('count', 0),
                f"{item.get('total_land', 0):.2f}",
                f"{item.get('avg_parcels', 0):.1f}"
            ])
        
        holding_table = Table(holding_data, colWidths=[1.5*inch, 1*inch, 1.5*inch, 1*inch])
        holding_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4caf50')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey)
        ]))
        story.append(holding_table)
        story.append(Spacer(1, 0.3*inch))
    
    # Irrigation Efficiency
    if 'irrigation_efficiency' in land_data:
        story.append(Paragraph("Irrigation Efficiency Analysis", heading_style))
        
        irrigation_data = [['System Type', 'Avg Efficiency', 'Avg Water Usage (m³)']]
        for item in land_data['irrigation_efficiency']:
            irrigation_data.append([
                item.get('system_type', '').title(),
                f"{item.get('avg_efficiency', 0):.1f}%",
                f"{item.get('avg_water_usage', 0):.0f}"
            ])
        
        irrigation_table = Table(irrigation_data, colWidths=[2*inch, 1.5*inch, 2*inch])
        irrigation_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2196f3')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey)
        ]))
        story.append(irrigation_table)
        story.append(Spacer(1, 0.3*inch))
    
    # Crop Productivity
    if 'crop_productivity' in land_data:
        story.append(Paragraph("Top Crop Productivity", heading_style))
        
        crop_data = [['Crop Name', 'Crop Type', 'Total Area (ha)', 'Avg Yield (tons)']]
        for item in land_data['crop_productivity'][:5]:  # Top 5 only
            crop_data.append([
                item.get('crop__name', ''),
                item.get('crop__crop_type', '').title(),
                f"{item.get('total_area', 0):.2f}",
                f"{item.get('avg_yield', 0):.2f}"
            ])
        
        crop_table = Table(crop_data, colWidths=[1.5*inch, 1.5*inch, 1.5*inch, 1.5*inch])
        crop_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#ff9800')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey)
        ]))
        story.append(crop_table)
        story.append(Spacer(1, 0.3*inch))
    
    # Recommendations
    story.append(Paragraph("Key Recommendations", heading_style))
    recommendations = [
        "• Review irrigation systems with efficiency below 70% for potential upgrades",
        "• Consider crop rotation to maintain soil health",
        "• Monitor water usage patterns for conservation opportunities",
        "• Analyze seasonal trends for better planting decisions",
        "• Regular soil testing recommended for all parcels"
    ]
    
    for rec in recommendations:
        story.append(Paragraph(rec, normal_style))
        story.append(Spacer(1, 0.1*inch))
    
    # Footer
    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph("Generated by AgriSite - Land Insights & Analysis Platform", 
                          ParagraphStyle('Footer', parent=styles['Normal'], alignment=TA_CENTER, fontSize=8)))
    
    # Build PDF
    doc.build(story)
    
    # Get PDF value from buffer
    pdf = buffer.getvalue()
    buffer.close()
    
    return pdf

def generate_parcel_detail_pdf(parcel, request):
    """Generate detailed PDF report for a specific land parcel"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    
    styles = getSampleStyleSheet()
    story = []
    
    # Title
    story.append(Paragraph(f"Land Parcel Report: {parcel.parcel_id}", 
                          ParagraphStyle('Title', parent=styles['Heading1'], alignment=TA_CENTER, textColor=colors.HexColor('#2e7d32'))))
    story.append(Spacer(1, 0.3*inch))
    
    # Parcel Details
    story.append(Paragraph("Parcel Details", styles['Heading2']))
    parcel_data = [
        ['Parcel ID:', parcel.parcel_id],
        ['Land Holder:', parcel.land_holder.name],
        ['Region:', parcel.land_holder.region.name],
        ['Total Area:', f"{parcel.total_area} hectares"],
        ['Cultivated Area:', f"{parcel.cultivated_area} hectares"],
        ['Soil Type:', parcel.get_soil_type_display()],
        ['Utilization Rate:', f"{(parcel.cultivated_area/parcel.total_area)*100:.1f}%"]
    ]
    
    parcel_table = Table(parcel_data, colWidths=[2*inch, 4*inch])
    parcel_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4caf50')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey)
    ]))
    story.append(parcel_table)
    
    return buffer.getvalue()