# Generated by Django 5.2.8 on 2025-11-10 23:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(choices=[('cereal', 'Cereal'), ('pulse', 'Pulse'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('cash', 'Cash Crop'), ('fodder', 'Fodder Crop')], max_length=20)),
                ('season', models.CharField(choices=[('kharif', 'Kharif (Monsoon)'), ('rabi', 'Rabi (Winter)'), ('zaid', 'Zaid (Summer)'), ('annual', 'Annual')], max_length=20)),
                ('growth_period', models.IntegerField(help_text='Growth period in days')),
                ('water_requirement', models.DecimalField(decimal_places=2, help_text='Water requirement in mm', max_digits=6)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LandHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ownership_type', models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate'), ('government', 'Government'), ('community', 'Community')], max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('total_area', models.DecimalField(decimal_places=2, help_text='Total area in hectares', max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(max_length=50, unique=True)),
                ('total_area', models.DecimalField(decimal_places=2, help_text='Area in hectares', max_digits=10)),
                ('cultivated_area', models.DecimalField(decimal_places=2, help_text='Area in hectares', max_digits=10)),
                ('soil_type', models.CharField(choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('loamy', 'Loamy'), ('silt', 'Silt'), ('peat', 'Peat'), ('chalky', 'Chalky')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('land_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='land_analysis.landholder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(auto_now_add=True)),
                ('soil_health_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('water_availability', models.IntegerField(help_text='Water availability percentage', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('productivity_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('recommendations', models.TextField(blank=True)),
                ('land_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='land_analysis.landparcel')),
            ],
            options={
                'verbose_name_plural': 'Land Analyses',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('drip', 'Drip Irrigation'), ('sprinkler', 'Sprinkler System'), ('flood', 'Flood Irrigation'), ('center_pivot', 'Center Pivot'), ('manual', 'Manual Irrigation'), ('none', 'No Irrigation')], max_length=20)),
                ('water_source', models.CharField(choices=[('well', 'Well'), ('canal', 'Canal'), ('river', 'River'), ('rain', 'Rainwater'), ('reservoir', 'Reservoir'), ('municipal', 'Municipal Water')], max_length=20)),
                ('efficiency_rating', models.IntegerField(help_text='Efficiency rating from 1-100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('annual_water_usage', models.DecimalField(decimal_places=2, help_text='Annual water usage in cubic meters', max_digits=10)),
                ('is_automated', models.BooleanField(default=False)),
                ('land_parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation', to='land_analysis.landparcel')),
            ],
        ),
        migrations.AddField(
            model_name='landholder',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land_analysis.region'),
        ),
        migrations.CreateModel(
            name='CroppingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.CharField(choices=[('kharif', 'Kharif (Monsoon)'), ('rabi', 'Rabi (Winter)'), ('zaid', 'Zaid (Summer)'), ('annual', 'Annual')], max_length=20)),
                ('area_allocated', models.DecimalField(decimal_places=2, help_text='Area in hectares', max_digits=10)),
                ('yield_amount', models.DecimalField(decimal_places=2, help_text='Yield in tons', max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, help_text='Revenue in local currency', max_digits=12)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land_analysis.crop')),
                ('land_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cropping_patterns', to='land_analysis.landparcel')),
            ],
            options={
                'ordering': ['-year', 'season'],
                'unique_together': {('land_parcel', 'crop', 'year', 'season')},
            },
        ),
    ]
